spring.application.name=app

# Put-off the Spring Boot banner.
spring.main.banner-mode=off

# ----------------------------- Messages -----------------------------
# Default message properties
# # This is inside the `message.properties` file

# Spanish properties
# This is inside the `message_es.properties` file

# English properties
# This is inside the `message_en.properties` file

# ----------------------------- MySQL Configuration -----------------------------
spring.datasource.url=jdbc:mysql://localhost:3306/pdwsdjpa
spring.datasource.username=root
spring.datasource.password=@folaFi081099

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
