spring.application.name=app

# Put-off the Spring Boot banner.
spring.main.banner-mode=off

# ----------------------------- Messages -----------------------------
# Default message properties
# # This is inside the `message.properties` file

# Spanish properties
# This is inside the `message_es.properties` file

# English properties
# This is inside the `message_en.properties` file
